product_name = input("Enter Product Name: ")
price = float(input("Enter Price: "))
quantity = float(input("Enter Quantity: "))
manufacturer = input("Enter Manufacturer: ")
print("\n" + "-" * 40)
print("PRODUCT CATALOG")
print("-" * 40)
print(f"{'Product Name':15}: {product_name}")
print(f"{'Price':15}: ₹{price:.2f}")
print(f"{'Quantity':15}: {quantity}")
print(f"{'Manufacturer':15}: {manufacturer}")
print("-" * 40)
print("Thank you for using the Product Catalog System!")